# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTQ4PG_r3YzZAFoFxqSHNA-3XKZb0wUU
"""

print("hello world")